services:
  sql-express:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-express
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"   # expose to host for debugging
    volumes:
      - sql-data:/var/opt/mssql

  todoapp-api:
    image: salehnawar/todolisttask-api:2.0
    container_name: todoapp-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-express;Database=TodoAppDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"   # API exposed on http://localhost:8080
      
    depends_on:
      - sql-express

volumes:
  sql-data:
